#!/usr/bin/env ts-node
/**
 * Generates observability/prometheus-rules.yml from alertRules.ts + additional
 * Prometheus-native rules (p99 latency, error rate, DB pool exhaustion).
 *
 * Usage: npm run generate:alert-rules
 */
import * as fs from "fs";
import * as path from "path";
import { rules } from "../src/utils/alertRules";

const GRAFANA_BASE = process.env.GRAFANA_URL ?? "http://localhost:3000";
const DASHBOARD_UID = "stellarkraal-backend";

function q(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function grafanaLink(name: string): string {
  return `${GRAFANA_BASE}/d/${DASHBOARD_UID}?var-alert=${encodeURIComponent(name)}`;
}

interface Rule {
  alert: string;
  expr: string;
  for: string;
  severity: string;
  summary: string;
  description?: string;
  runbook: string;
  dashboard: string;
}

function renderRule(r: Rule, indent = 6): string {
  const pad = " ".repeat(indent);
  const lines = [
    `${pad}- alert: ${r.alert}`,
    `${pad}  expr: ${q(r.expr)}`,
    `${pad}  for: ${r.for}`,
    `${pad}  labels:`,
    `${pad}    severity: ${r.severity}`,
    `${pad}  annotations:`,
    `${pad}    summary: ${q(r.summary)}`,
  ];
  if (r.description) lines.push(`${pad}    description: ${q(r.description)}`);
  lines.push(`${pad}    runbook: ${q(r.runbook)}`);
  lines.push(`${pad}    dashboard: ${q(r.dashboard)}`);
  return lines.join("\n");
}

const metricRules: Rule[] = [
  {
    alert: "HighP99Latency",
    expr: "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1",
    for: "2m",
    severity: "warning",
    summary: "p99 HTTP latency exceeds 1s",
    description: "p99 latency is {{ $value | humanizeDuration }} over the last 5 minutes.",
    runbook: `${GRAFANA_BASE}/d/${DASHBOARD_UID}`,
    dashboard: grafanaLink("HighP99Latency"),
  },
  {
    alert: "HighErrorRate",
    expr: 'sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.01',
    for: "1m",
    severity: "critical",
    summary: "HTTP 5xx error rate exceeds 1%",
    description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes.",
    runbook: `${GRAFANA_BASE}/d/${DASHBOARD_UID}`,
    dashboard: grafanaLink("HighErrorRate"),
  },
  {
    alert: "DbPoolExhaustion",
    expr: "db_pool_available == 0",
    for: "30s",
    severity: "critical",
    summary: "DB connection pool exhausted",
    description: "All DB pool connections are in use — new queries will queue or fail.",
    runbook: `${GRAFANA_BASE}/d/${DASHBOARD_UID}`,
    dashboard: grafanaLink("DbPoolExhaustion"),
  },
];

const appRules: Rule[] = Object.values(rules).map((rule) => {
  const alertName = rule.id
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  return {
    alert: alertName,
    expr: `stellarkraal_alert_fired{rule="${rule.id}"} > 0`,
    for: `${Math.round(rule.cooldownMs / 60000)}m`,
    severity: rule.severity,
    summary: rule.name,
    runbook: `https://github.com/teslims2/StellarKraal-/blob/main/docs/runbooks/${rule.runbook}`,
    dashboard: grafanaLink(rule.id),
  };
});

const allRules = [...metricRules, ...appRules].map((r) => renderRule(r)).join("\n");

const yaml = `# Auto-generated by scripts/generate-alert-rules.ts — do not edit manually
groups:
  - name: stellarkraal.rules
    rules:
${allRules}
`;

const outPath = path.resolve(__dirname, "../../observability/prometheus-rules.yml");
fs.writeFileSync(outPath, yaml, "utf8");
console.log(`Written: ${outPath}`);
